# **Introduction to NumPy**


<center>
    <img src=https://studyopedia.com/wp-content/uploads/2022/03/numpy-big-logo-300x300.png>
</center>

# NumPy (short for Numerical Python) is a powerful library in Python used for numerical computation.
 
# It provides support for arrays (especially multidimensional ones), along with a wide range of mathematical functions to operate on them efficiently.

# ndarray: Its core feature is the ndarray object, an efficient multidimensional array. 

## Install Numpy using Pip

```python
import numpy as np
```

In [1]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip



# **Numpy vs. Lists**

In [3]:
# pip install numpy # to install numpy library
import numpy as np
# below, a and b are normal lists
a = [1,2,3,4]
b = [2,4,6,7]
type(a)
type(b)

list

## Try to multiply these

## MATRIX MULTIPLICATION 

# BASIC PYTHON STYLE


<center>
    <img src = https://miro.medium.com/v2/resize:fit:640/format:webp/1*G0i-4NVQFPNi6C7QVmSgiQ.gif>
</center>


[Stolen From](https://medium.com/data-science-collective/learning-triton-one-kernel-at-a-time-matrix-multiplication-44851b4146dd)

In [ ]:
a*b # trying to multiply them

## Now using NUMPY

In [7]:
# below a and b are numpby arrays 
a = np.array([1,2,3,4])
b = np.array([2,4,6,7])
a*b
#print(a_into_b)

array([ 2,  8, 18, 28])


<center>
    <img src = https://matteding.github.io/images/broadcasting-col-row.gif>
</center>


[Stolen From](https://matteding.github.io/2019/04/11/numpy-broadcasting/)

In [24]:
oneD = np.array([1,3,4,5],dtype='int16')
twoD = np.array([[4,3,2,1],[9,7,6,5]])

print(oneD.dtype)
print(twoD)

int16
[[4 3 2 1]
 [9 7 6 5]]


# Using %timeit Magic Command

In [26]:
%timeit mylist = [1,2,3]

57.9 ns ± 1.17 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [28]:
%timeit import numpy; myarray = numpy.array([1,2,3])

723 ns ± 19.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [31]:
%timeit mylist = list(range(1000000))

26.2 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
%timeit import numpy; myarray = numpy.arange(1000000)

2.84 ms ± 120 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Whats the Speed

In [36]:
# importing required packages
import numpy
import time

# size of arrays and lists
size = 1000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = numpy.arange(size) 
array2 = numpy.arange(size)

# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists :", 
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
resultantArray = array1 * array2

# calculating execution time 
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


Time taken by Lists : 0.13020658493041992 seconds
Time taken by NumPy Arrays : 0.004355430603027344 seconds


# MORE EXAMPLES

In [38]:
# importing required packages
import numpy
import time


# size of arrays and lists
size = 1000000

# declaring lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# Concatenation
print("\nConcatenation:")

# list
initialTime = time.time()
list1 = list1 + list2

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = numpy.concatenate((array1, array2),
						axis = 0)

# calculating execution time 
print("Time taken by NumPy Arrays :", 
	(time.time() - initialTime),
	"seconds")


# Dot Product
dot = 0
print("\nDot Product:")

# list
initialTime = time.time()
for a, b in zip(list1, list2):
		dot = dot + (a * b)
		
# calculating execution time
print("Time taken by Lists :", 
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = numpy.dot(array1, array2)

# calculating execution time 
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


# Scalar Addition 
print("\nScalar Addition:")

# list
initialTime = time.time()
list1 =[i + 2 for i in range(size)]

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array1 = array1 + 2

# calculating execution time 
print("Time taken by NumPy Arrays :", 
	(time.time() - initialTime), 
	"seconds")


# Deletion
print("\nDeletion: ")

# list
initialTime = time.time()
del(list1)

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
del(array1)

# calculating execution time 
print("Time taken by NumPy Arrays :", 
	(time.time() - initialTime),
	"seconds")



Concatenation:
Time taken by Lists : 0.02523064613342285 seconds
Time taken by NumPy Arrays : 0.006003379821777344 seconds

Dot Product:
Time taken by Lists : 0.18804502487182617 seconds
Time taken by NumPy Arrays : 0.003003358840942383 seconds

Scalar Addition:
Time taken by Lists : 0.10035538673400879 seconds
Time taken by NumPy Arrays : 0.0029997825622558594 seconds

Deletion: 
Time taken by Lists : 0.009994745254516602 seconds
Time taken by NumPy Arrays : 0.0009984970092773438 seconds


In [4]:
from time import time
import numpy as np

def timer_func(func):
    # This function shows the execution time of 
    # the function object passed
    def wrap_func(*args, **kwargs):
        t1 = time()
        result = func(*args, **kwargs)
        t2 = time()
        print(f'Function {func.__name__!r} executed in {(t2-t1):.4f}s')
        return result
    return wrap_func


@timer_func
def long_time(n):
    for i in range(n):
        for j in range(100000):
            i*j

out_time = range(100000)
in_time = range(100000)
out_t = np.array(out_time)  
in_t = np.array(in_time)
@timer_func
def nump(out_time):
    np.array(in_time) * np.array(out_time)



In [5]:
long_time(1000)

Function 'long_time' executed in 4.9894s


In [6]:
nump(out_time)

Function 'nump' executed in 0.0203s


## Why NumPy Outperforms Lists (NumPy is faster)
1. Memory Layout
Python Lists: Store references (pointers) to objects scattered across memory. Each element can be of a different type, so extra metadata is needed.
NumPy Arrays: Store homogeneous data (all elements of the same type) in contiguous memory blocks, like a C array. This reduces memory overhead and improves cache efficiency.
Think of lists as a messy bookshelf with boxes of mixed items, while NumPy arrays are neatly stacked, identical books.

2. Vectorization
Lists require explicit for-loops in Python, which are slow because Python executes them line by line.
NumPy arrays allow vectorized operations (e.g., array1 * array2) that run in compiled C code underneath, avoiding Python’s interpreter overhead.
Example: Multiplying two arrays of size 1,000,000 takes milliseconds in NumPy vs. seconds in lists.

3. Broadcasting
NumPy can automatically expand smaller arrays to match larger ones during operations, avoiding manual looping or reshaping.
Lists cannot do this; you must write nested loops.

# **NumPy: Dimension and Shape**

print(oneD.ndim)
print(oneD.shape)
print(twoD.ndim)
print(oneD.shape)

# **NumPy: Memory Size**
# On Windows, NumPy defaults its base integer to the C language long type, which is strictly 32 bits (4 bytes) per element, even if your computer processor is 64-bit. If you ran the exact same code on macOS or Linux, it would default to int64, which can be changed for better memory utilisation

In [11]:
print(oneD.dtype)
updated_oneD_dtype = np.array([1,3,4,5,5,6,7],dtype='int16')
updated_oneD_dtype.dtype

int16


dtype('int16')

# **NumPy: Get a Specific Element [r, c]**

In [12]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,110]])
arr[1,3] # we get 9 
arr[0,3] # we get 4
arr[0,:] # we get the first list in arr or the first row
# How to get the second list of rows?
arr[:,2] # we column 2, which 3 and 8
arr[0,3:5] # what is the output
arr[1,4] = 20 # updating values 
print(arr)

[[  1   2   3   4   5]
 [  6   7   8   9  20]
 [ 16  17  18  19 110]]


# **NumPy: Generate Random values in an array**

In [14]:
#np.ones((1,4,2)) # Two 2D array of 4x4
#np.full((4,2),5) # One 2D array of 4x4 with values 5
#np.random.rand(4,2) # One 2D of random values of 4x2
#np.empty((2,3))
np.random.randint(100, size = (10,2)) # find out?

array([[71, 62],
       [21, 29],
       [60, 64],
       [43, 45],
       [85, 90],
       [73,  8],
       [32, 96],
       [26, 12],
       [49, 55],
       [82, 85]], dtype=int32)

# Lambda Function


In [22]:
addd = lambda a : a + 10
print(addd(15))

25


# Multiplicatioon of two digits using Lambda Function

In [40]:
add = lambda a, b : a * b
print(add(5, 6))

30


# Slicing and Indexing

In [42]:
arr = np.array(range(100))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Reshape Data

<center>
    <img src = https://assets.truemeds.in/Images/ProductImage/TM-TACR1-049067/reshape-natural-tablet-10_reshape-natural-tablet-10--TM-TACR1-049067_1.png>
</center>



In [44]:
arr = np.array(range(100)).reshape((10,10)) # To reshape data

In [45]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# **DIY (NumPy: Statistic Functions)**
# Create a 3D Array and perform the following operation.
# 1. Max
# 2. Min
# 3. Mean
# 4. Mode
# 5. Median


# **Dictionaries**
# Similar to actual dictionaries

# They are effectively 2 lists, combined keys and values
# We use the keys to access the values instead of indexing them like a list
# Each value is mapped to a unique key


# Hint Use the help command

In [16]:
student = {
    "S_name":"Akash",
    "S_ID":"2026cs001",
    "S_email":"akash.in@gmail.com"}
print(student)
type(student)

{'S_name': 'Akash', 'S_ID': '2026cs001', 'S_email': 'akash.in@gmail.com'}


dict

In [17]:
students = {
    "S_name":["Akash","Puja","Lina","Rawina"],
    "S_ID":["2026cs001","2026cs002","2026cs003"],
    "S_email":["akash.in@gmail.com","puja@gmail.com","lina@gmail.com","rawina@gmail.com"]}
#int(students)
#print(students.keys())  # get only the keys of th dictionary
#print(students.values()) # get only the values
#students.update({"S_name":"Lina"})
#print(students)
students.pop("S_ID")
print(students)

{'S_name': ['Akash', 'Puja', 'Lina', 'Rawina'], 'S_email': ['akash.in@gmail.com', 'puja@gmail.com', 'lina@gmail.com', 'rawina@gmail.com']}


In [18]:
students = {
    "S_name":["Akash","Puja","Lina","Rawina"],
    "S_ID":["2026cs001","2026cs002","2026cs003"],
    "S_email":["akash.in@gmail.com","puja@gmail.com","lina@gmail.com","rawina@gmail.com"]}
#print(students)
indexvalue = students['S_name'].index("Puja")
students['S_name'][indexvalue]= "Priyanka"
print(students)

{'S_name': ['Akash', 'Priyanka', 'Lina', 'Rawina'], 'S_ID': ['2026cs001', '2026cs002', '2026cs003'], 'S_email': ['akash.in@gmail.com', 'puja@gmail.com', 'lina@gmail.com', 'rawina@gmail.com']}
